name: TModsServerAddons_InfiniteFlight
main: me.tmods.serveraddons.InfFlight
version: 1.13
author: Timo Hocker
website: http://timosmods.weebly.com

depends:
 - TModsServerUtils

commands:
  InfFlight:
    description: toogle infinteflight mode
    usage: /infflight
